### ISSUE TITLE
Measure storm datarate

### ISSUE THREAD

**Issue by mackaiver** [mackaiver/streams-cta#11]
Originally reported by: **AEgorov (Bitbucket: [AEgorov](http://bitbucket.org/AEgorov), GitHub: [AEgorov](http://github.com/AEgorov))**

----------------------------------------

Measure datarate performance on a storm cluster.

* Vollmond: nimbus, zookeeper, publisher
* create ``default.yaml`` containing needed configuration
* tell *storm* nodes where to find ``default.yaml``
* using the current version *streams-storm* start multiple workers
* measure data rate of the storm cluster 

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/streams-cta/issue/11

**Comment by alexeyegorov** [comment]
This issue was important for CTA meeting. Current comparison of spark, storm and flink are "under construction".
