### ISSUE TITLE
Screenshots of Storm UI

### ISSUE THREAD

**Issue by mackaiver** [mackaiver/streams-cta#16]
Originally reported by: **AEgorov (Bitbucket: [AEgorov](http://bitbucket.org/AEgorov), GitHub: [AEgorov](http://github.com/AEgorov))**

----------------------------------------

Create some screenshots of storm UI containing following:

* overview of nodes, workers, topologies, ...
* supervisors should be **different** machines (not the same IP)
* running topology overview showing latencies and executions numbers
* showing visualization of a ``streams`` process
    * use more processors this time
    * processors and the whole process should make some sense

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/streams-cta/issue/16

**Comment by alexeyegorov** [comment]
This was a task for CTA meeting and was done but not marked as resolved.
