### ISSUE TITLE
Setup Jenkins Server

### ISSUE THREAD

**Issue by mackaiver** [mackaiver/streams-cta#3]
Originally reported by: **Christian Bockermann (Bitbucket: [cbockermann](http://bitbucket.org/cbockermann), GitHub: [cbockermann](http://github.com/cbockermann))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/streams-cta/issue/3

**Comment by alexeyegorov** [comment]
CI is integrated into github.
