### ISSUE TITLE
Somehow connect python to the whole shebang

### ISSUE THREAD

**Issue by mackaiver** [mackaiver/streams-cta#39]
Not sure how to go about this yet. I'll explore 

- JPY jpy.readthedocs.io
- JEP https://github.com/mrj0/jep
- Maybe MsgPack RPC

**Comment by mackaiver** [comment]
So it turns out that:

- JPY and JEP are really messy to install
- messagepack-rpc for python is no longer maintained

So for now I'm sticking with https://pythonhosted.org/Pyro4/ and https://github.com/irmen/Pyrolite.
See PR #40

**Comment by alexeyegorov** [comment]
This is somehow resolved now, right? Can we close this issue?
