### ISSUE TITLE
Messaging queues

### ISSUE THREAD

**Issue by mackaiver** [mackaiver/streams-cta#5]
Originally reported by: **AEgorov (Bitbucket: [AEgorov](http://bitbucket.org/AEgorov), GitHub: [AEgorov](http://github.com/AEgorov))**

---
- ZeroMQ Api TCP Queue introspection
- ZeroMQ seems to drop some messages at publisher (change PUB/SUB to sth else?)
- Kafka
- ActiveMQ has a [redelivery policy](http://activemq.apache.org/message-redelivery-and-dlq-handling.html)
- ~~ IronMQ introduced [**Error Queues**](http://www.iron.io/blog/2014/01/push-queues-error-queues-better-queue.html) to [retry sending](http://www.iron.io/blog/2013/01/ironmq-push-queues-reliable-message.html) failed messages ~~ IronMQ is not free! :-1: 

---
- Bitbucket: https://bitbucket.org/cbockermann/streams-cta/issue/5

**Comment by alexeyegorov** [comment]
is not needed anymore!
